name: pictora
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  dropdown_textfield: ^1.2.0

  intl: ^0.20.2
  fluttertoast: ^8.2.12
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  path: ^1.9.0
  http: ^1.2.2
  dio: ^5.8.0+1
  http_parser: ^4.0.2
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc_concurrency: ^0.3.0
  go_router: ^16.0.0
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.2.0
  insta_assets_picker: ^3.3.0
  shimmer: ^3.0.0
  video_player: ^2.10.0
  photo_manager: ^3.7.1
  carousel_slider: ^5.1.1
  video_thumbnail: ^0.5.6
  timeago: ^3.7.1
  visibility_detector: ^0.4.0+2
  pinch_zoom_release_unzoom: ^2.0.0
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
